# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3, 5)
print(A)
print()
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [3]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print(B)
print()
print(C)
print()
print("Elementwise Subtraction")
print(B - C)
print()
print("Elementwise Multiplication")
print(B * C)
print()
print("Matrix Multiplication")
print(B @ C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [4]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()
print("Exponentiate each number elementwise")
print(np.exp(B))
print()
print("Calculate the minimum value in the whole matrix")
print(np.min(B))
print()
print("Calculate the minimum value in each row")
print(np.min(B, axis=1))
print()
print("Calculate the minimum value in each column")
print(np.min(B, axis=0))
print()
print("Find the index value for the minimum value in the whole matrix")
print(np.argmin(B))
print()
print("Find the index value for the minimum value in each row")
print(np.argmin(B, axis=1))
print()
print("Calculate the sum for all elements")
print(np.sum(B))
print()
print("Calculate the mean for each column")
print(np.mean(B, axis=0))
print()
print("Calculate the median for each column")
print(np.median(B, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiate each number elementwise
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Calculate the minimum value in the whole matrix
1

Calculate the minimum value in each row
[1 4 7]

Calculate the minimum value in each column
[1 2 3]

Find the index value for the minimum value in the whole matrix
0

Find the index value for the minimum value in each row
[0 0 0]

Calculate the sum for all elements
45

Calculate the mean for each column
[4. 5. 6.]

Calculate the median for each column
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [5]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [7]:
# In the example above, A[1] returns the second row of the array A,
# So when you provide fewer indices than axes
# the code assume that you want to full slice of the remaining axes. Meaning the whole row.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print("Row:", i)
    print("Elements", end=": ")
    for j in i:
        print(j, end=", ")
    print()

Row: [1 2 3 4 5]
Elements: 1, 2, 3, 4, 5, 
Row: [ 6  7  8  9 10]
Elements: 6, 7, 8, 9, 10, 
Row: [11 12 13 14 15]
Elements: 11, 12, 13, 14, 15, 


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [10]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [11]:
# First line:
#   Create range() like object from 0 to 29

# Second line:
#   Using the elements, reshape the 30 elements into 2 matrices, with each matrix having 3 rows.
#   Then calculate (-1) programmatically how many elements each row will have (5 in this case).

# b is now a 3D array. To access a specific element, you would have to specify 3 indices.
print(b[0, 2, 3])

13


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [13]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2, 2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [15]:
def add_mul_matrices(m1, m2, operation):
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise ValueError("m1 or m2 are not the type of instance 'np.ndarray'")

    if operation == "add":
        if m1.shape != m2.shape:
            raise ValueError("Matrices have different sizes")
        return m1 + m2

    elif operation == "multiply":
        if m1.shape[1] != m2.shape[0]:
            raise ValueError("Matrices have incompatible shapes")
        return m1 @ m2

    raise ValueError("Invalid operation")

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [16]:
x = np.array([[4, 3]])
print(x)
# a) 1x2
print(x.shape)
# b)
print("Beräkna 5x")
print(x * 5)
# c)
print("Beräkna 3x")
print(x * 3)
# d)
print("Beräkna 5x + 3x")
print(x * 5 + x * 3)
# e)
print("Beräkna 8x")
print(x * 8)
# f)
print("Beräkna 4x - x")
print(x * 4 - x)
# g)
x_t = x.transpose()
print("Transponerad x:")
print(x_t)
print("Nya dimensionen är 2x1")
print(x_t.shape)
# h)
print("Definierat") if x.shape == x_t.shape else print("Ej definierat")
# i)
print("Beräkna ||x||")
print(np.linalg.norm(x))

[[4 3]]
(1, 2)
Beräkna 5x
[[20 15]]
Beräkna 3x
[[12  9]]
Beräkna 5x + 3x
[[32 24]]
Beräkna 8x
[[32 24]]
Beräkna 4x - x
[[12  9]]
Transponerad x:
[[4]
 [3]]
Nya dimensionen är 2x1
(2, 1)
Ej definierat
Beräkna ||x||
5.0


In [17]:
print("UPPGIFT 10.1.2")
v = np.array([[3], [7], [0], [11]])
print(v)
# a)
print(
    f"Vektorn har dimensionen {str(v.shape).replace(",","x").replace(" ", "")}"
)
# b)
print("Beräkna 2v")
print(v * 2)
# c)
print("Beräkna 5v + 2v")
print(v * 5 + v * 2)
# d
print("Beräkna 4v - 2v")
print(v * 4 - v * 2)
# e
v_t = v.transpose()
print("Efter transponeringen är dimensionen nu 1x4", v_t)
print(v_t.shape)
# f
print("Beräkna ||v||")
print(np.linalg.norm(v))

UPPGIFT 10.1.2
[[ 3]
 [ 7]
 [ 0]
 [11]]
Vektorn har dimensionen (4x1)
Beräkna 2v
[[ 6]
 [14]
 [ 0]
 [22]]
Beräkna 5v + 2v
[[21]
 [49]
 [ 0]
 [77]]
Beräkna 4v - 2v
[[ 6]
 [14]
 [ 0]
 [22]]
Efter transponeringen är dimensionen nu 1x4 [[ 3  7  0 11]]
(1, 4)
Beräkna ||v||
13.379088160259652


In [18]:
print("Uppgift 10.1.3")
v_1 = np.array([[4, 3, 1, 5]])
v_2 = np.array([[2, 3, 1, 1]])

print("a) Beräkna ||v_1||")
print(np.linalg.norm(v_1))
print("b) Beräkna  ||v1 - v2||")
print(np.linalg.norm(v_1 - v_2))

Uppgift 10.1.3
a) Beräkna ||v_1||
7.14142842854285
b) Beräkna  ||v1 - v2||
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [19]:
print("Uppgift 10.2.1")
A = np.array([(2, 1, -1), (1, -1, 1)])
B = np.array([(4, -2, 1), (2, -4, -2)])
C = np.array([(1, 2), (2, 1)])
D = np.array([(3, 4), (4, 3)])
E = np.array([[1], [2]])
I = np.array([(1, 0), (0, 1)])
print("A")
print(A)
print("B")
print(B)
print("C")
print(C)
print("D")
print(D)
print("E")
print(E)
print("I")
print(I)

Uppgift 10.2.1
A
[[ 2  1 -1]
 [ 1 -1  1]]
B
[[ 4 -2  1]
 [ 2 -4 -2]]
C
[[1 2]
 [2 1]]
D
[[3 4]
 [4 3]]
E
[[1]
 [2]]
I
[[1 0]
 [0 1]]


In [20]:
print("a) 2A")
print(A * 2)
print("b) B - 2A")
print(B - A * 2 if B.shape == A.shape else "Undefined")
print("c) 3C - 2E")
print(C * 3 if C.shape == E.shape else "Undefined")
print("d) 2D - 3C")
print(D * 2 - 3 * C if  D.shape == C.shape else "Undefined")
print("e) D_T + 2D")
print(D.transpose() + D * 2 if (D.transpose().shape == D.shape and D.transpose().shape == D.shape) else "Undefined")
print("f) 2C_T - 2D_T")
print(C.transpose() * 2 - D.transpose() * 2 if C.transpose().shape == D.transpose().shape else "Undefined")
print("g) A_T - B")
print(A.transpose() - B if A.transpose().shape == B.shape else "Undefined")
print("h) A @ C")
print(A @ C if A.shape[1] == C.shape[0] else "Undefined")
print("i) C @ D")
print(C @ D if C.shape[1] == D.shape[0] else "Undefined")
print("j) C @ B")
print(C @ B if C.shape[1] == B.shape[0] else "Undefined")
print("k) C @ I")
print(C @ I if C.shape[1] == I.shape[0] else "Undefined")
print("l) A @ B_T")
print(A @ B.transpose() if A.shape[1] == B.transpose().shape[0] else "Undefined")

a) 2A
[[ 4  2 -2]
 [ 2 -2  2]]
b) B - 2A
[[ 0 -4  3]
 [ 0 -2 -4]]
c) 3C - 2E
Undefined
d) 2D - 3C
[[3 2]
 [2 3]]
e) D_T + 2D
[[ 9 12]
 [12  9]]
f) 2C_T - 2D_T
[[-4 -4]
 [-4 -4]]
g) A_T - B
Undefined
h) A @ C
Undefined
i) C @ D
[[11 10]
 [10 11]]
j) C @ B
[[  8 -10  -3]
 [ 10  -8   0]]
k) C @ I
[[1 2]
 [2 1]]
l) A @ B_T
[[5 2]
 [7 4]]


In [21]:
print("Uppgift 10.2.2")
A = np.array([[2, 3, 4], [5, 4, 1]])
print(A)
print("A @ A_T")
print(
    A @ A.transpose() if A.shape[1] == A.transpose().shape[0] else "Undefined"
)

Uppgift 10.2.2
[[2 3 4]
 [5 4 1]]
A @ A_T
[[29 26]
 [26 42]]


In [22]:
print("Uppgift 10.2.3")
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])
AB = A @ B
AC = A @ C
print(AB)
print(AC)
print(AB == AC)
print(B == C)

Uppgift 10.2.3
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [23]:
v1 = np.arange(4)
v2 = v1[-2:]

print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [24]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [25]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [26]:
# When we create a view it actually holds the references to the same object in memory.